### ISSUE TITLE
Messages not formated

### ISSUE THREAD

**Issue by PhML** [pavel-kazhavets/AlertmanagerRocketChat#1]
I used the provided js script as this and the sent messages are not formated:

![screenshot-2017-6-7 rus chat 1](https://user-images.githubusercontent.com/1955673/26868204-726fe2e4-4b68-11e7-9b8e-b3e08f44574d.png)

Is there some configuration from RocketChat side to do?

**Comment by Cosaquee** [comment]
I have the same problem now after upgrading to latest Rocket.Chat version.

**Comment by tholu** [comment]
Same problem here, please accept the Pull Request #2 @pavel-kazhavets - or is this repository not maintained anymore?

**Comment by tholu** [comment]
Thank you! 👍
